#!/bin/bash

######################################
##        MAIN APP EASYIWD
######################################

netact=("dynamic" "static" "disconnect")

easyiwd_head() {
	clear
	echo "----------------------------------------------------------------"
	echo "                         EASSY IWD                              "
	echo "                                                  "
	echo "----------------------------------------------------------------"
	echo ""
	echo "Bugs Report"
	echo "[1] muhammadhaydarilhamkamil <kamilhaydar03@gmail.com>"
	echo "----------------------------------------------------------------"
	echo ""
}

easyiwd_scanall() {
	sudo iwctl station wlan0 get-networks
	sudo iwctl device list
}

easyiwd_contdyn() {
	easyiwd_scanall &&
		read -p "add network name :" netname
	if [[ ! -z $netname ]]; then
		iwctl station wlan0 connect $netname
		easyiwd_netstat
	fi
}

easyiwd_netstat() {

	status=$(iwctl staion wlan0 show | grep -i state)

	if [[ $status == *"connected"* ]]; then
		echo "network connected"
	else
		echo "network not connected"
	fi
}

easyiwd_intconf() {
	read -p "Address   :" address
	read -p "Netmask   :" netmask
	read -p "Gateway   :" gateway
	read -p "broadcast :" broadcs
	read -p "DNS       :" dnsnets

}

easyiwd_constat() {

	easyiwd_contdyn &&
		easyiwd_intconf &&
		local iwdefin=('Address' 'Netmask' 'Gateway' 'Broadcast' 'DNS')
	local iwvalue=($address $netmask $gateway $broadcs $dnsnets)
	echo "-------------------------------------------------"
	echo "Network Configuration"
	for i in ${!iwdefin[@]}; do
		echo "${iwdefin[i]} = ${iwvalue[i]}"
	done

}

easyiwd_settdns() {
	sudo cat <<EOF >/etc/resolv.conf
nameserver $dnsnets
EOF
}

easyiwd_setstat() {
	touch /var/lib/iwd/$netname.psk
	sudo cat <<EOF >/var/lib/iwd/$netname.psk
[IPv4]
Address=$address
Netmask=$netmask
Gateway=$gateway
Broadcast=$broadcs
DNS=$dnsnets  
EOF
}

easyiwd_intsysd() {
	touch /etc/systemd/network/$netname.network
	sudo cat <<EOF >/etc/systemd/network/$netname.network
[match]

EOF
}

easyiwd_initenc() {
	sudo cat <<EOF >/etc/iwd/main.conf
[General]
EnableNetworkConfiguration=true
EOF
}

easyiwd_iwdconf() {
	if [[ ! -f /etc/iwd/main.conf ]]; then
		sudo touch /etc/iwd/main.conf
		easyiwd_initenc
	fi
}

easyiwd_netmenu() {
	echo "chose your method :"
	for method in "${!netact[@]}"; do
		echo "[$(($method + 1))] ${netact[$method]}"
	done
	read -p "select method using number : " getact
	iwdact=${netact[$(($getact - 1))]}
}

easyiwd_connect() {
	easyiwd_netmenu &&
		if [[ $iwdact == "dynamic" ]]; then
			clear
			easyiwd_contdyn
		elif [[ $iwdact == "static" ]]; then
			clear
			easyiwd_constat
		elif [[ $iwdact == "disconnect" ]]; then
			iwctl station wlan0 disconnect
			echo "Network disconnect"
		else
			echo "error you must enter the correct number"
		fi

}
easyiwd_init() {
	easyiwd_head
	easyiwd_iwdconf
	easyiwd_connect
}

easyiwd_init

#persimple tampilan hanya ada 2 pilihan static dan dynamic
#scan dan device langsung ditampilkan

#masing masing fitur deradapat scan dan scan hidden
#dynamic connect biasa dan connect hidden
