#!/bin/bash

######################################
##        MAIN APP EASYIWD          ##
######################################

easyiwd_head() {
	clear
	echo "----------------------------------------------------------------"
	echo "                         EASSY IWD                              "
	echo "                     copyright@HaydarK03                                             "
	echo "----------------------------------------------------------------"
	echo ""
	echo "Bugs Report"
	echo "[1] muhammadhaydarilhamkamil <kamilhaydar03@gmail.com>"
	echo "----------------------------------------------------------------"
	echo ""
}

easyiwd_contdyn() {
	read -p "add network name :" netname
	if [[ ! -z $netname ]]; then
		iwctl station wlan0 connect $netname
		echo "Network Connected"
	else
		echo "error network name incorect"
		exit
	fi
}

easyiwd_intconf() {
	read -p "Address   :" address
	read -p "Netmask   :" netmask
	read -p "Gateway   :" gateway
	read -p "broadcast :" broadcs
	read -p "DNS       :" dnsnets

}

easyiwd_constat() {
	easyiwd_contdyn &&
		easyiwd_intconf &&
		local iwdefin=('Address' 'Netmask' 'Gateway' 'Broadcast' 'DNS')
	local iwvalue=($address $netmask $gateway $broadcs $dnsnets)
	echo "-------------------------------------------------"
	echo "Network Configuration"
	for i in ${!iwdefin[@]}; do
		echo "${iwdefin[i]} = ${iwvalue[i]}"
	done

}

easyiwd_netmenu() {
	local netact=("dynamic" "static" "scan device" "disconnect")
	echo "chose your method :"
	for method in "${!netact[@]}"; do
		echo "[$(($method + 1))] ${netact[$method]}"
	done
	read -p "select method using number : " getact
	iwdact=${netact[$(($getact - 1))]}

}

easyiwd_connect() {
	iwctl station wlan0 get-networks &&
		easyiwd_netmenu &&
		if [[ $iwdact == "dynamic" ]]; then
			easyiwd_contdyn
		elif [[ $iwdact == "static" ]]; then
			easyiwd_constat
		elif [[ $iwdact == "scan device" ]]; then
			iwctl device list
		elif [[ $iwdact == "disconnect" ]]; then
			iwctl station wlan0 disconnect
			echo "Network disconnect"
		else
			echo "error you must enter the correct number"
		fi

}
easyiwd_init() {
	easyiwd_head
	easyiwd_connect
}

easyiwd_init
